# Generated by Django 6.0 on 2025-12-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='updates_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='updates_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updates_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='doughtype',
            old_name='updates_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='updates_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updates_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
