# Generated by Django 6.0 on 2025-12-09 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_updates_at_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
