# Generated by Django 6.0 on 2025-12-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productsize_created_at_productsize_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category'),
        ),
    ]
