# Generated by Django 6.0 on 2025-12-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productsize_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='category',
        ),
    ]
