# Generated by Django 6.0 on 2025-12-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_productsize_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='editable',
        ),
        migrations.AddField(
            model_name='productsize',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='doughtype',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category'),
        ),
    ]
