# Generated by Django 6.0 on 2025-12-15 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_price_productingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
    ]
