# Generated by Django 6.0 on 2025-12-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productingredient_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredient', to='shop.product'),
        ),
    ]
