# Generated by Django 6.0 on 2025-12-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_productingredient_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dough_types',
            field=models.ManyToManyField(to='shop.doughtype'),
        ),
        migrations.CreateModel(
            name='CategoryProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsize')),
            ],
        ),
    ]
