# Generated by Django 6.0 on 2025-12-15 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_dough_types_categoryproductsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproductsize',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product_size', to='shop.category'),
        ),
    ]
