# Generated by Django 5.2.7 on 2025-10-28 10:18

from django.db import migrations, models
import hashlib


def generate_uids(apps, schema_editor):
    User = apps.get_model("user", "User")
    for user in User.objects.filter(uid__isnull=True):
        base_str = f"{user.pk}-{user.username or ''}-{user.email}"
        user.uid = hashlib.sha256(base_str.encode()).hexdigest()[:8]
        user.save(update_fields=["uid"])


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='', editable=False, help_text='Уникальный идентификатор для обмена контактами.', max_length=8, unique=True),
        ),
        migrations.RunPython(generate_uids, reverse_code=migrations.RunPython.noop),
    ]
