# Generated by Django 6.0 on 2025-12-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('code', models.CharField(editable=False, max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updates_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoginCode',
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.role'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['target', 'type'], name='user_verifi_target_cdeb31_idx'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
