# Generated by Django 6.0 on 2025-12-09 09:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='updates_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('content_maker', 'Content maker'), ('owner', 'Owner')], default='client'),
        ),
    ]
