# Generated by Django 6.0 on 2025-12-23 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role_verificationcode_alter_contact_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user',
        ),
        migrations.RenameField(
            model_name='verificationcode',
            old_name='updates_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='code',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='_code_hash',
            field=models.CharField(db_column='code', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'device_id'], name='user_userde_user_id_9f2a27_idx'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='unique_user_device'),
        ),
    ]
